/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdBanner: typeof import('./components/AdBanner.vue')['default']
    BalanceInfoCard: typeof import('./components/BalanceInfoCard.vue')['default']
    BankCardForm: typeof import('./components/BankCardForm.vue')['default']
    BankCardSelector: typeof import('./components/BankCardSelector.vue')['default']
    BannerCarousel: typeof import('./components/BannerCarousel.vue')['default']
    BottomTabbar: typeof import('./components/BottomTabbar.vue')['default']
    CustomerServiceButton: typeof import('./components/CustomerServiceButton.vue')['default']
    DomainPopup: typeof import('./components/DomainPopup.vue')['default']
    GlobalAuthModal: typeof import('./components/GlobalAuthModal.vue')['default']
    GlobalCustomerServiceModal: typeof import('./components/GlobalCustomerServiceModal.vue')['default']
    GuestTipModal: typeof import('./components/GuestTipModal.vue')['default']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    HomeEntryPopup: typeof import('./components/HomeEntryPopup.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LoadingStates: typeof import('./components/LoadingStates.vue')['default']
    PrimaryMenu: typeof import('./components/PrimaryMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SecondaryMenu: typeof import('./components/SecondaryMenu.vue')['default']
    TopLoading: typeof import('./components/TopLoading.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VideoList: typeof import('./components/VideoList.vue')['default']
    VideoPagination: typeof import('./components/VideoPagination.vue')['default']
    VideoSection: typeof import('./components/VideoSection.vue')['default']
  }
}

// For TSX support
declare global {
  const AdBanner: typeof import('./components/AdBanner.vue')['default']
  const BalanceInfoCard: typeof import('./components/BalanceInfoCard.vue')['default']
  const BankCardForm: typeof import('./components/BankCardForm.vue')['default']
  const BankCardSelector: typeof import('./components/BankCardSelector.vue')['default']
  const BannerCarousel: typeof import('./components/BannerCarousel.vue')['default']
  const BottomTabbar: typeof import('./components/BottomTabbar.vue')['default']
  const CustomerServiceButton: typeof import('./components/CustomerServiceButton.vue')['default']
  const DomainPopup: typeof import('./components/DomainPopup.vue')['default']
  const GlobalAuthModal: typeof import('./components/GlobalAuthModal.vue')['default']
  const GlobalCustomerServiceModal: typeof import('./components/GlobalCustomerServiceModal.vue')['default']
  const GuestTipModal: typeof import('./components/GuestTipModal.vue')['default']
  const HeaderNav: typeof import('./components/HeaderNav.vue')['default']
  const HomeEntryPopup: typeof import('./components/HomeEntryPopup.vue')['default']
  const IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
  const LoadingStates: typeof import('./components/LoadingStates.vue')['default']
  const PrimaryMenu: typeof import('./components/PrimaryMenu.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchBar: typeof import('./components/SearchBar.vue')['default']
  const SecondaryMenu: typeof import('./components/SecondaryMenu.vue')['default']
  const TopLoading: typeof import('./components/TopLoading.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanSwipe: typeof import('vant/es')['Swipe']
  const VanSwipeItem: typeof import('vant/es')['SwipeItem']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabs: typeof import('vant/es')['Tabs']
  const VideoList: typeof import('./components/VideoList.vue')['default']
  const VideoPagination: typeof import('./components/VideoPagination.vue')['default']
  const VideoSection: typeof import('./components/VideoSection.vue')['default']
}